import pandas as pd
import nltk
from sklearn.svm import SVC
from sklearn import tree, svm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
# nltk.download('averaged_perceptron_tagger')
# nltk.download('wordnet')
# nltk.download('punkt')
from convert_to_lowercase import convert_to_lowercase
from remove_stop_words import remove_stop_words
from remove_punctuation import remove_punctuation
from remove_slangs import remove_slangs
from remove_extra_spaces import remove_extra_spaces
from lemmatization_text import lemmatization_text
from text_normalization import Converting_To_Primitive

from sklearn.datasets import load_breast_cancer
import matplotlib.pyplot as plt
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.svm import SVC

emotional_states = [
    'victimized',
    'accused',
    'acquitted',
    'adorable',
    'adored',
    'affected',
    'afflicted',
    'aghast',
    'agog',
    'agonized',
    'alarmed',
    'amused',
    'angry',
    'anguished',
    'animated',
    'annoyed',
    'anxious',
    'apathetic',
    'appalled',
    'appeased',
    'appreciated',
    'apprehensive',
    'ardent',
    'aroused',
    'attached',
    'attracted',
    'autonomous',
    'awed',
    'awkward',
    'belonging',
    'bereaved',
    'betrayed',
    'bewildered',
    'bitter',
    'blissful',
    'blithe',
    'blocked',
    'blue',
    'bold',
    'bored',
    'brave',
    'bright',
    'brisk',
    'calm',
    'capable',
    'captivated',
    'careless',
    'categorized',
    'cautious',
    'certain',
    'chagrined',
    'challenged',
    'chastised',
    'cheated',
    'cheerful',
    'cheerless',
    'cheery',
    'cherished',
    'chicken',
    'cocky',
    'codependent',
    'coerced',
    'comfortable',
    'common',
    'competent',
    'complacent',
    'composed',
    'concerned',
    'confident',
    'confused',
    'connected',
    'conned',
    'consumed',
    'contented',
    'controlled',
    'convivial',
    'cornered',
    'courageous',
    'cowardly',
    'craving',
    'crestfallen',
    'criticized',
    'cross',
    'crushed',
    'curious',
    'daring',
    'dark',
    'dedicated',
    'defeated',
    'defenseless',
    'degraded',
    'dejected',
    'depressed',
    'deserted',
    'desirable',
    'despondent',
    'detached',
    'determined',
    'diminished',
    'disappointed',
    'discarded',
    'disconsolate',
    'discontented',
    'discounted',
    'discouraged',
    'disgraced',
    'disgusted',
    'disheartened',
    'disillusioned',
    'disjointed',
    'dismal',
    'dismayed',
    'disoriented',
    'disparaged',
    'displeased',
    'disrespected',
    'distressed',
    'distrustful',
    'dolorous',
    'doubtful',
    'down',
    'downhearted',
    'dreadful',
    'dreary',
    'dubious',
    'dull',
    'duped',
    'eager',
    'earnest',
    'ecstatic',
    'elated',
    'embarrassed',
    'empathetic',
    'enchanted',
    'encouraged',
    'engrossed',
    'enraged',
    'enterprising',
    'enthusiastic',
    'entrusted',
    'esteemed',
    'excited',
    'excluded',
    'exempt',
    'exhilarated',
    'exploited',
    'exposed',
    'fabulous',
    'fainthearted',
    'fantastic',
    'fascinated',
    'favored',
    'fearful',
    'fervent',
    'fervid',
    'festive',
    'flat',
    'focused',
    'forced',
    'forsaken',
    'framed',
    'free',
    'frightened',
    'frisky',
    'frustrated',
    'fuming',
    'funereal',
    'furious',
    'gallant',
    'genial',
    'glad',
    'gleeful',
    'gloomy',
    'glum',
    'grieved',
    'guilt',
    'guilty',
    'happy',
    'hardy',
    'heartbroken',
    'hesitant',
    'hilarious',
    'hopeful',
    'horny',
    'horrified',
    'humiliated',
    'humorous',
    'hurt',
    'hysterical',
    'ignored',
    'immobilized',
    'immune',
    'important',
    'impotent',
    'imprisoned',
    'incensed',
    'included',
    'indecisive',
    'independent',
    'indignant',
    'infatuated',
    'inflamed',
    'injured',
    'inquisitive',
    'insignificant',
    'intent',
    'interested',
    'intrigued',
    'irate',
    'irresolute',
    'irresponsible',
    'irritated',
    'isolated',
    'jaunty',
    'jocular',
    'jolly',
    'jovial',
    'joyful',
    'joyless',
    'joyous',
    'jubilant',
    'keen',
    'labeled',
    'lackadaisical',
    'lazy',
    'liked',
    'lively',
    'livid',
    'lonely',
    'lonesome',
    'lost',
    'loved',
    'lucky',
    'macho',
    'mad',
    'melancholy',
    'menaced',
    'merry',
    'mirthful',
    'misunderstood',
    'moody',
    'moping',
    'motivated',
    'mournful',
    'needed',
    'needy',
    'nervous',
    'obligated',
    'obsessed',
    'offended',
    'oppressed',
    'optionless',
    'ordinary',
    'organized',
    'outmaneuvered',
    'outraged',
    'overjoyed',
    'overlooked',
    'overwhelmed',
    'panicked',
    'passionate',
    'passive',
    'peaceful',
    'pensive',
    'perplexed',
    'phobic',
    'playful',
    'pleased',
    'powerless',
    'pressured',
    'privileged',
    'proud',
    'provoked',
    'punished',
    'quaking',
    'quiescent',
    'rageful',
    'rapturous',
    'rated',
    'reassured',
    'reckless',
    'redeemed',
    'regretful',
    'rejected',
    'released',
    'remorse',
    'replaced',
    'repulsed',
    'resentful',
    'resolute',
    'respected',
    'responsible',
    'restful',
    'revered',
    'rueful',
    'sad',
    'satisfied',
    'saucy',
    'scared',
    'secure',
    'serene',
    'shaky',
    'shamed',
    'shocked',
    'significant',
    'skeptical',
    'snoopy',
    'somber',
    'sparkling',
    'spirited',
    'spiritless',
    'sprightly',
    'startled',
    'stereotyped',
    'stifled',
    'strong',
    'suffering',
    'sulky',
    'sullen',
    'sunny',
    'surprised',
    'suspicious',
    'sympathetic',
    'tense',
    'terrified',
    'terrorized',
    'thankful',
    'threatened',
    'thwarted',
    'timid',
    'timorous',
    'torn',
    'tortured',
    'tragic',
    'tranquil',
    'transported',
    'trapped',
    'tremulous',
    'tricked',
    'unbelieving',
    'uncertain',
    'unconcerned',
    'unfocussed',
    'unlovable',
    'unloved',
    'unmotivated',
    'unshackled',
    'unsupported',
    'validated',
    'valued',
    'victimized',
    'violated',
    'virulent',
    'vivacious',
    'vulnerable',
    'wavering',
    'weak',
    'welcomed',
    'woebegone',
    'woeful',
    'worried',
    'worshiped',
    'wrathful',
    'wronged',
    'yearning',
    'yellow',
    'zealous',
    'abandoned',
    'absolved',
    'absorbed',
    'abused',
    'accepted',
    'aching',
    'acrimonious',
    'addicted',
    'adequate',
    'admired',
    'affectionate',
    'affronted',
    'afraid',
    'airy',
    'alone',
    'ambivalent',
    'apathetic',
    'apprehensive',
    'arrogant',
    'ashamed',
    'astonished',
    'attacked',
    'audacious',
    'average',
    'avid',
    'baffled',
    'bashful',
    'belittled',
    'buoyant',
    'burdened',
    'clouded',
    'committed',
    'compassionate',
    'compelled',
    'dauntless',
    'debonair',
    'deceived',
    'delighted',
    'demoralized',
    'derailed',
    'desirous',
    'despairing',
    'devastated',
    'diffident',
    'discredited',
    'disheartened',
    'disinclined',
    'disorganized',
    'downcast',
    'entitled',
    'excited',
    'exultant',
    'fidgety',
    'frowning',
    'great',
    'hapless',
    'hated',
    'heroic',
    'hostile',
    'indifferent',
    'infuriated',
    'insecure',
    'inspired',
    'inspiring',
    'judged',
    'justified',
    'laughting',
    'loved',
    'loving',
    'low',
    'lustful',
    'manipulated',
    'mumpish',
    'nosey',
    'numb',
    'obliterated',
    'peaceful',
    'petrified',
    'piqued',
    'piteous',
    'powerless',
    'questioning',
    'rejected',
    'satisfied',
    'sorrowful',
    'spirited',
    'supported',
    'suspicious',
    'terrific',
    'trapped',
    'trembling',
    'uncomfortable',
    'underestimated',
    'unhappy',
    'vindicated'
]

data = pd.read_csv('../sentimentdataset.csv')

data = remove_extra_spaces(data)

data = convert_to_lowercase(data, 'Text')

data = convert_to_lowercase(data, 'Sentiment (Label)')

data['Text'] = data['Text'].apply(remove_punctuation)

data['Text'] = data['Text'].apply(remove_stop_words)

data['Text'] = data['Text'].apply(remove_slangs)

data['Sentiment (Label)'] = data['Sentiment (Label)'].apply(Converting_To_Primitive)

data['Text'] = data['Text'].apply(lemmatization_text)

X = data['Text']
Y = data['Sentiment (Label)']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

featureExtraction = TfidfVectorizer(min_df= 1, stop_words= emotional_states, lowercase=True)

X_train_features = featureExtraction.fit_transform(X_train)
X_test_features = featureExtraction.transform(X_test)

# logisticRegModel = LogisticRegression().fit(X_train_features, y_train)
# y_pred1 = logisticRegModel.predict(X_test_features)

svmModel = svm.SVC(kernel='linear').fit(X_train_features, y_train)
y_pred3 = svmModel.predict(X_test_features)

print('The accuracy for Logistic Regression Classifer:',accuracy_score(y_test,y_pred3)*100)

# text = "Just published a new blog post. Check it out!"

# text = remove_punctuation(text)
# print(text)